#!/bin/bash
# Only for Linux
if [[ $(uname) != 'Linux' ]] ; then echo "Only valid for Linux kernel" ; exit 1 ; fi

# Determine init version for correct execution
if [ -d /etc/systemd ]
then
  echo "Installing Chef Habitat systemd unit using {{pkg.svc_config_install_path}}/hab-sup.service"
  ## Make sure there is not already a unit configured
  if [[ $(grep -qr 'hab sup' /etc/systemd) ]]
  then
    echo 'Chef Habitat supervisor already has systemd unit configured:'
    grep -r 'hab sup' /etc/systemd
    exit 1
  fi
  ## Install systemd unit
  cp {{pkg.svc_config_install_path}}/hab-sup.service /etc/systemd/system/
  systemctl daemon-reload
  ## Enable systemd unit
  systemctl enable hab-sup
  systemctl start hab-sup
elif [ -d /etc/init.d ]
then
  echo "Installing Chef Habitat service using {{pkg.svc_config_install_path}}/hab-sup.initd"
  ## Make sure there is not already a unit configured
  if [[ $(grep -qr 'hab sup' /etc/init.d) ]]
  then
    echo 'Chef Habitat supervisor already has systemd unit configured:'
    grep -r 'hab sup' /etc/init.d
    exit 1
  fi
  ## Install service
  cp {{pkg.svc_config_install_path}}/hab-sup.initd /etc/init.d/hab-sup
  chmod +x /etc/init.d/hab-sup
  ## Enable service
  chkconfig hab-sup on
  echo "hab-sup service has been installed!"
  echo "Start the Habitat supervisor with command 'sudo service hab-sup start'"
else
  echo "not using systemd or initd under standard paths, exiting"
fi

# Verify that Supervisor config file is present
if [ ! -f /hab/sup/default/config/sup.toml ]
then
  echo 'Attempting to create /hab/sup/default/config/sup.toml'
  mkdir -p /hab/sup/default/config
  hab sup run --generate-config > /hab/sup/default/config/sup.toml  ; echo 'Supervisor config file created.' || echo 'Could not generate config file.'
fi
