#!/bin/bash
# Only for Linux
if [[ $(uname) != 'Linux' ]] ; then echo "Only valid for Linux kernel" ; exit 1 ; fi

# Determine init version for correct execution
if [ -d /etc/systemd ]
then
  echo "Installing Chef Habitat systemd unit using {{pkg.svc_config_install_path}}/hab-sup.service"
  ## Make sure there is not already a unit configured
  if [[ $(grep -qr 'hab sup' /etc/systemd) ]]
  then
    echo 'Chef Habitat supervisor already has systemd unit configured:'
    grep -r 'hab sup' /etc/systemd
    exit 1
  fi
  ## Install systemd unit
  cp {{pkg.svc_config_install_path}}/hab-sup.service /etc/systemd/system/
  systemctl daemon-reload
  ## Enable systemd unit
  systemctl enable hab-sup
  systemctl start hab-sup
  exit 0
elif [ -d /etc/init.d ]
then
  echo "Installing Chef Habitat service using"
  ## Make sure there is not already a unit configured
  if [[ $(grep -qr 'hab sup' /etc/init.d) ]]
  then
    echo 'Chef Habitat supervisor already has systemd unit configured:'
    grep -r 'hab sup' /etc/init.d
    exit 1
  fi
  ## Install service
  cp {{pkg.svc_config_install_path}}/hab-sup.initd /etc/init.d/hab-sup
  chmod +x /etc/init.d/hab-sup
  ## Enable service
  service hab-sup start
  chkconfig hab-sup on
  exit 0
else
  echo "not using systemd or initd under standard paths, exiting"
fi
