name: hab_sup_service CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Code
      uses: actions/checkout@v2
    - name: Install Chef Habitat
      uses: collinmcneese/chef-habitat-install@master
    - name: Build and Install
      run: |
        hab origin key generate
        hab pkg build .
        if [ ! -f results/last_build.env ] ; then echo "build failed!" ; exit 1 ; fi
      env:
        HAB_LICENSE: accept-no-persist
        HAB_ORIGIN: collinmcneese
